events {}
http {
    include /etc/nginx/mime.types;
    server_tokens off;
    client_max_body_size 20M;
    resolver 127.0.0.11 valid=10s ipv6=off;
    server {
        listen 80;
        server_name aspectfy.ru www.aspectfy.ru;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name aspectfy.ru www.aspectfy.ru;
        ssl_certificate /etc/letsencrypt/live/aspectfy.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/aspectfy.ru/privkey.pem;
        location /api/ {
            set $upstream_backend backend:8000;
            proxy_pass http://$upstream_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
       
        location /ws/ {
            set $upstream_ws backend-ws:8001;
            proxy_pass http://$upstream_ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /static/ {
            alias /var/lib/static/;
        }
        location /media/ {
            alias /var/lib/media/;
        }
       
        location ~ ^/(admin|feed|profile|organization|notifications|search|chats|sign-in|sign-up|password)(\/.*)?$ {
            set $upstream_frontend frontend:80;
            proxy_pass http://$upstream_frontend/index.html;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
            set $upstream_frontend frontend:80;
            proxy_pass http://$upstream_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_intercept_errors on;
            error_page 404 = @spa_fallback;
        }
        location @spa_fallback {
            set $upstream_frontend frontend:80;
            proxy_pass http://$upstream_frontend/index.html;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
