# Generated by Django 5.2.11 on 2026-02-25 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0008_post_post_author_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', '-created_at'], name='notif_recipient_read_idx'),
        ),
    ]
