# Generated by Django 5.2.11 on 2026-02-25 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_options_alter_like_unique_together_and_more'),
        ('posts', '0008_post_post_author_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', '-created_at'], name='like_post_created_idx'),
        ),
    ]
