# Generated by Django 5.2.11 on 2026-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_organizationsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization Subscription', 'verbose_name_plural': 'Organization Subscriptions'},
        ),
    ]
