# Generated by Django 5.2.11 on 2026-02-19 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_avatar'),
        ('subscriptions', '0003_alter_organizationsubscription_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationsubscription',
            name='unique_organization-subscription',
        ),
        migrations.AddConstraint(
            model_name='organizationsubscription',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_organization_subscription'),
        ),
    ]
