# Generated by Django 5.2.11 on 2026-02-25 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_avatar'),
        ('subscriptions', '0004_remove_organizationsubscription_unique_organization_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['follower', '-created_at'], name='orgsub_follower_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['follower', '-created_at'], name='sub_follower_created_idx'),
        ),
    ]
