# Generated by Django 5.2.11 on 2026-02-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
