# Generated by Django 5.2.7 on 2026-02-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='awards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
