# Generated by Django 5.2.11 on 2026-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_user_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
