# Generated by Django 5.2.7 on 2026-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
