# Generated by Django 5.2.11 on 2026-02-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
