# Generated by Django 5.2.11 on 2026-02-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_avatar'),
        ('posts', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.organization'),
        ),
    ]
