# Generated by Django 5.2.11 on 2026-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_post_author_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
