# Generated by Django 5.2.11 on 2026-02-19 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_organization'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_post',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_user',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='unique_report_per_post'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('reporter', 'user'), name='unique_report_per_user'),
        ),
    ]
