# Generated by Django 5.2.11 on 2026-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/org/%Y/%m/%d/'),
        ),
    ]
