# Generated by Django 5.2.11 on 2026-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
