# Generated by Django 5.2.11 on 2026-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/org/%Y/%m/%d/'),
        ),
    ]
